[package]
name = "laura_core"
version = "0.1.0"
edition = "2021"
authors = ["HansTibberio <hanstiberio@proton.me>"]
description = "A WIP chess engine in Rust."
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess"]
categories = ["games"]

include = ["src/*", "cargo.toml"]

[lib]
name = "laura_core"
path = "src/lib.rs"