name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" , "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy
    - name: Fmt
      run: cargo fmt --all -- --check
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
